### ISSUE TITLE
No connection could be made because the target machine actively refused it 127.0.0.1:9200 

### ISSUE THREAD

**Issue by mahalakshmibv** [damienbod/ElasticsearchCRUD#128]
No connection could be made because the target machine actively refused it 127.0.0.1:9200 

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:9200

Tool: visual studio 2012(MVC application)
OS:windows

**Comment by damienbod** [comment]
This seems like a firewall problem. See if you can reach http://localhost:9200 in your browser, then you can find out if elasticsearch can be accessed with this URL). Or try turning off the firewall or allow access for this address. 

greetings Damien
