### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by prince4prodigy** [damienbod/ElasticsearchCRUD#135]
Authentication failed because the remote party has closed the transport stream.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

I use `ssl` in my project.
VS 2015(MVC application), Windows

**Comment by damienbod** [comment]
I'll have a look at this, I never tested the library with https

Greetings Damien

**Comment by prince4prodigy** [comment]
My problem is  solved with rebuild project.

**Comment by damienbod** [comment]
cool
Greetings Damien
