### ISSUE TITLE
Dependency "System.Net.Http": "4.0.1-rc2-23513" not found

### ISSUE THREAD

**Issue by Schwenkner** [damienbod/ElasticsearchCRUD#148]
I'm trying the package 2.0.2.1-rc1 together wit .Net Core. But I get the error message in the subject. It seems, this dependency is gone.

Can the package be updated?

**Comment by damienbod** [comment]
Hi @Schwenkner 
I'm using the following src
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="MyGet" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
I think its from myget.

Once RC2 is released, I will update this properly to use only NuGet as it's feed.

If you add this to your NuGet config, it will find the package.

Hope this helps

Greetings Damien

**Comment by Schwenkner** [comment]
Thanks for the fast answer. It worked at a glance.
