### ISSUE TITLE
Why not supports .NET Framework 4.5.1,4.5.2,4.6,netstandard1.6?

### ISSUE THREAD

**Issue by mikeandersun** [damienbod/ElasticsearchCRUD#156]
```
Package ElasticsearchCrud 2.3.3.1 is not compatible with net46 (.NETFramework,Version=v4.6). 
Package ElasticsearchCrud 2.3.3.1 supports: netstandard1.4 (.NETStandard,Version=v1.4)
One or more packages are incompatible with .NETFramework,Version=v4.6.

```

**Comment by damienbod** [comment]
Hi Mike

Here's and example net461, supported by netstandard1.4:
https://github.com/damienbod/WebSearchWithElasticsearch
(check the packages to see what's needed)

Here's a .net core app
https://github.com/damienbod/WebAppAspNet50ElasticsearchCrud

net451 will not be supported.

net452, undecided about this, these apps could be updated to net461

My main reason was that it's too much work to support two versions, and I assume in 6 months most will have switched to net462, net463 or net core.

What do you require, suggestion?

Greetings Damien

**Comment by mikeandersun** [comment]
Hi Damien, 
I require make `frameworks` section of `project.json` as below:
```
 "frameworks": {
        "net451": {},
        "net452": {},
        "net46": {},
        "netcoreapp1.6": {
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    }
```

**Comment by damienbod** [comment]
Ok, I'll see what I can do, net451 should be removed as this is no longer a supported .NET.
netcoreapp1.6 should be no problem, net46 and net452, I need to check.

Greetings Damien

**Comment by mikeandersun** [comment]
Thanks.I'm waiting for your decision.
It is better to have a gitter to chat.

**Comment by mikeandersun** [comment]
Please add `NuGet.Config` to repo.

**Comment by damienbod** [comment]
Ok, net451 and net 452 causes to many type conflicts. 
```javascript
    "frameworks": {
        "netstandard1.4": {
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ],
            "dependencies": {
                "Newtonsoft.Json": "9.0.1",
                "System.ComponentModel.Annotations": "4.1.0",
                "System.Net.Http": "4.1.0",
                "System.Reflection.TypeExtensions": "4.1.0",
                "System.Console": "4.0.0",
                "System.Diagnostics.TraceSource": "4.0.0"
            }
        },
        "netcoreapp1.6": {
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ],
            "dependencies": {
                "Newtonsoft.Json": "9.0.1",
                "System.ComponentModel.Annotations": "4.1.0",
                "System.Net.Http": "4.1.0",
                "System.Reflection.TypeExtensions": "4.1.0",
                "System.Console": "4.0.0",
                "System.Diagnostics.TraceSource": "4.0.0"
            }
        },
        "net46": {
            "dependencies": {
                "Newtonsoft.Json": "9.0.1",
                "System.ComponentModel.Annotations": "4.0.10.0",
                "System.Net.Http": "4.1.0",
                "System.Reflection.TypeExtensions": "4.1.0",
                "System.Console": "4.0.0",
                "System.Diagnostics.TraceSource": "4.0.0"
            }
        }
    }
```

**Comment by damienbod** [comment]
I'll create a beta version, I have to test. 

I made a mess of the integration tests and need to change these all back NUnit, then I can run quicker for all configurations.

**Comment by damienbod** [comment]
Do we still need a NuGet.config?

**Comment by damienbod** [comment]
The first test aren't working, this will take time, I will create a new branch for this, strange effects with the VS tooling...

Greetings Damien

**Comment by mikeandersun** [comment]
No, You can remove it (`Nuget.config`) from the solution too.

**Comment by damienbod** [comment]
netstandard1.4 covers n461 and higher.
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md
