### ISSUE TITLE
Getting 'Parameter Count Mismatch' Exception on bulk insert

### ISSUE THREAD

**Issue by markmcgookin** [damienbod/ElasticsearchCRUD#161]
Tried using latest version of Elasticsearch and 2.3.1 both with the same result.

Using ElasticsearchCRUD 2.3.1.1 on Linux with .Net core. 

Doing multiple inserts always fails with the exception

> Unhandled Exception: ElasticsearchCRUD.ElasticsearchCrudException: Parameter count mismatch.
   at ElasticsearchCRUD.Utils.SyncExecute.<ExecuteResultDetails>b__3_1[T](Exception x)
   at System.AggregateException.Handle(Func`2 predicate)
   at ElasticsearchCRUD.Utils.SyncExecute.ExecuteResultDetails[T](Func`1 method)
   at Rig.Data.ElasticSearchProvider.AddUpdateBatch(List`1 records)
   at Rig.Program.Main(String[] args)

Individual inserts work fine, however it's much slower than doing it in bulk. The code used is as follow.

```
public void AddUpdateBatch(List<AppRecord> records)
        {
            //Avoids any with a duplicate hash
            foreach(var record in records.GroupBy(r => r.Hash).Select(grp => grp.First()))
            {
                _context.AddUpdateDocument(records, record.Hash);
            }
            _context.SaveChanges();
}
```

**Comment by damienbod** [comment]
Hi @markmcgookin, I will have a look at this. Could you post the AppRecord class, it would help investigating the problem.

Greetings Damien

**Comment by damienbod** [comment]
I will test using 2.4.1

**Comment by damienbod** [comment]
Tried to reproduce the bug using the following without success (With and without the IndexCreate)
```
public void Setup()
{
	var doc1 = new SearchTest
	{
		Id = 1,
		Details = "This is the details of the document, very interesting",
		Name = "one",
		CircleTest = new GeoShapeCircle { Radius = "100m", Coordinates = new GeoPoint(45, 45) },
		Location = new GeoPoint(45, 45),
		Lift = 2.9,
		DateOfDetails = DateTime.UtcNow.AddDays(-20)
	};

	var doc2 = new SearchTest
	{
		Id = 2,
		Details = "Details of the document two, leave it alone",
		Name = "two",
		CircleTest = new GeoShapeCircle { Radius = "50m", Coordinates = new GeoPoint(46, 45) },
		Location = new GeoPoint(46, 45),
		Lift = 2.5,
		DateOfDetails = DateTime.UtcNow.AddDays(-209)
	};
	var doc3 = new SearchTest
	{
		Id = 3,
		Details = "This data is different",
		Name = "three",
		CircleTest = new GeoShapeCircle { Radius = "80m", Coordinates = new GeoPoint(37, 42) },
		Location = new GeoPoint(37, 42),
		Lift = 2.1,
		DateOfDetails = DateTime.UtcNow.AddDays(-34)
	};
	using (var context = new ElasticsearchContext(ConnectionString, ElasticsearchMappingResolver))
	{
		if (!context.IndexExists<SearchTest>())
		{
			context.IndexCreate<SearchTest>();
			Thread.Sleep(1500);
			context.AddUpdateDocument(doc1, doc1.Id);
			context.AddUpdateDocument(doc2, doc2.Id);
			context.AddUpdateDocument(doc3, doc3.Id);
			context.SaveChanges();
			Thread.Sleep(1500);
		}				
	}
}
```

**Comment by markmcgookin** [comment]
Hey, the index creation was done through kibana/sense using an elkstack docker creation. 

App Record is fairly simple.

```
public class AppRecord
    {
        public AppRecord() { }

        public AppRecord(AppLinkMetadata metadata)
        {
            AppId = metadata.Id;
            Hash = metadata.Hash;
            Url = metadata.Url;
            Title = metadata.Title;
            ShortName = metadata.DeveloperShortName;
        }

        public long Id { get; set; }
        public string AppId { get; set; }
        public string Hash { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string ShortName { get; set; }
    }
```

Currently the AppData index is being created manually, however, it will be done in code going forward.

```
POST /appdata_20161006
{
	"settings": {
		"number_of_shards": 5,
		"number_of_replicas": 0,
		"analysis": {
			"char_filter": {
				"separator_pattern_filter": {
					"type": "pattern_replace",
					"pattern": "(?:\\\\)+",
					"replacement": "/"
				},
				"path_normalising_filter": {
					"type": "pattern_replace",
					"pattern": "(?:.+:)?(.*)\/.*",
					"replacement": "$1"
				},
				"filename_pattern_filter": {
					"type": "pattern_replace",
					"pattern": "(.*)\/.*",
					"replacement": "$1"
				}
			},
			"analyzer": {
				"filepath_analyser": {
					"type": "custom",
					"char_filter": ["separator_pattern_filter",
					"filename_pattern_filter"],
					"tokenizer": "filepath_tokenizer"
				}
			},
			"tokenizer": {
				"filepath_tokenizer": {
					"type": "path_hierarchy",
					"delimiter": "/"
				}
			}
		}
	},
	"mappings": {
		"apple_apps": {
			"properties": {
				"Id": {
					"type": "long"
				},
				"AppId": {
					"type": "string"
				},
				"Hash": {
					"type": "string"
				},
				"Url": {
					"type": "string"
				},
				"Title": {
					"type": "string"
				},
				"ShortName": {
					"type": "string"
				}
			}
		}
	}
}
```

**Comment by damienbod** [comment]
I've created a demo project for you

https://github.com/damienbod/BulkInsertTestElasticsearch

The AddRecord class requires a special mapping because per default all properties are set to lower case. Because you use ID and not id, this needs to be mapped.

I created this index and the mapping using your script and then added the documents. 

Greetings Damien

**Comment by markmcgookin** [comment]
Amazing mate, 

Thanks for the great support! 

Apologies, I never noticed that.

**Comment by damienbod** [comment]
Thanks

**Comment by markmcgookin** [comment]
Hey buddy, 

Thanks for your help on this... It turns out that this was a code issue. 

The line:
` _context.AddUpdateDocument(records, record.Hash);`

should have been 

`_context.AddUpdateDocument(record, record.Hash);`

I had tried to pass in the collection and not the object. One 's' out of place. I've left your mapping in, as I assume that is good practice anyway when using strange indexes like mine.

Thanks for the help.
