### ISSUE TITLE
Error during initializing mappings with child objects

### ISSUE THREAD

**Issue by MrGorki** [damienbod/ElasticsearchCRUD#163]
I am trying to implement the MVC application with EntityFramework and Elasticsearch guide
(https://damienbod.com/2014/11/02/mvc-application-with-entity-framework-and-elasticsearch/)

but having

"ElasticsearchCRUD.ElasticsearchCrudException: No Key found for child object" error on elasticSearchContext.SaveChangesAndInitMappings();

Actually the object giving this error has [Key] and [DatabaseGenerated(DatabaseGeneratedOption.Identity)] attributes 

StackTrace:
```
ElasticsearchCrudException: No Key found for child object: User]
   ElasticsearchCRUD.Utils.SyncExecute.<ExecuteResultDetails>b__3_1(Exception x) +136
   System.AggregateException.Handle(Func`2 predicate) +54
   ElasticsearchCRUD.Utils.SyncExecute.ExecuteResultDetails(Func`1 method) +317
   ElasticsearchCRUD.ContextAddDeleteUpdate.ElasticsearchContextAddDeleteUpdate.SaveChanges(List`1 entityPendingChanges, Boolean saveChangesAndInitMappingsForChildDocuments) +109
   ElasticsearchCRUD.ElasticsearchContext.SaveChangesAndInitMappings() +20
   xxx.ElasticSearch.InitializeSearchEngine.SaveToElasticsearchJobIfitDoesNotExist() in C:\xxx\ElasticSearch\ElasticSearch.cs:94
   xxx.MvcApplication.Application_Start() in C:\xxx\Global.asax.cs:229

[HttpException (0x80004005): No Key found for child object: User]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9982013
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): No Key found for child object: User]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9963380
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
```

**Comment by damienbod** [comment]
Hi @MrGorki 

Could you send me your DTOs or entities, which you want to index?

Greetings Damien

**Comment by MrGorki** [comment]
Hi @damienbod !

Of course but I believe it is a little bit mess. Too much relations going on..
I did add your source code as project and tried to investigate the problem. It seems some unwanted relations are also trying to get into the game. Do I have any chance to eliminate  the unwanted relations to be created? 

Because on my context almost everyinthing has relation in somehow but I want to use only 2 or 3 of them only.

Anyhow; how can I send my model to you in private?

**Comment by damienbod** [comment]
Thanks, yes maybe DTOs for the elastic model might be better, depends how you want to use the data after.

damien_bod1@hotmail.com

Greetings Damien

**Comment by MrGorki** [comment]
I want to do indexing for searching. My current listing is going on through "Is" table and it is resolving the relations during search.

So I want to index "Is" and do the search on top of this index.

**Comment by damienbod** [comment]
Also at present only elasticsearch 2.X is supported, I want to update to 5.0.0, lots of breaking changes. Plan to do a new version before XMAS, sometime this month.

**Comment by MrGorki** [comment]
@damienbod Unfortunately and actually unnecessarily yes :)
I think JsonIgnore will do! Thats what I was looking for. 

Thanks for your helps! I will keep this thread updated. Version 5.0.0 will be perfect also!

Best,
G.

**Comment by MrGorki** [comment]
Now, I did clean it up mostly. My search model is almost ready as you guide. 
 But I am getting new error now during the serialization of ICollection<> types

 ```
private void ProcessArrayOrCollection(EntityContextInfo entityInfo, ElasticsearchCrudJsonWriter elasticsearchCrudJsonWriter, PropertyInfo prop, bool createPropertyMappings)
        {
            TraceProvider.Trace(TraceEventType.Verbose, "ElasticsearchMapping: IsPropertyACollection: {0}", prop.Name.ToLower());

            if (createPropertyMappings && prop.GetValue(entityInfo.Document) == null)
            {
                if (prop.PropertyType.IsArray)
                {
                    prop.SetValue(entityInfo.Document, Array.CreateInstance(prop.PropertyType.GetElementType(), 0));
                }
                else
                {
  **HERE --->**   prop.SetValue(entityInfo.Document, Activator.CreateInstance(prop.PropertyType));
                }	
            }
```

**Comment by damienbod** [comment]
Could you try replacing the ICollection with a List<>, I don't think I have supported ICollection. 

Greetings Damien

**Comment by MrGorki** [comment]
Thanks Damien!
You are absolutely right. List solved the problem but now a new challenge appears :)
DbGeography type (spatial) is returning 'No parameterless constructor defined for this object'

Opps :(

Best!

**Comment by MrGorki** [comment]
OK. I've fixed it by changing Activator.CreateInstance into FormatterServices.GetUninitializedObject and also adding DbGeography type to be catched along with System.Decimal as you already defined like;

prop.PropertyType.GetTypeInfo().IsClass && prop.PropertyType.FullName != "System.String" && prop.PropertyType.FullName != "System.Decimal" && prop.PropertyType.FullName != "System.Data.Entity.Spatial.DbGeography"

**Comment by MrGorki** [comment]
Now a new challenge appeared :) 

It looks like you don't allow an object to have two parent object :( It looks like trouble for me. I am am investigating to overcome this one. 

I will appreciate your suggestions :)

Best!

**Comment by MrGorki** [comment]
OK. I've changed all the structure and create a single ViewModel for indexing. I am selecting all the required fields to this single model and trying to index it but DbGeography again making a problem. Do you faced any similar?

**Comment by damienbod** [comment]
Hi @MrGorki DbGeography cannot be serialized, you can ignore it or create a special mapping to a geo type which is a bit tricky.

Greetings Damien

**Comment by MrGorki** [comment]
Ok will try to map to double as coordinates then. Thanks!

**Comment by MrGorki** [comment]
Ok. Everything works fine now I am closing it. Thank you very much once more for sharing your time.

Best,
G.

**Comment by damienbod** [comment]
super, delighted it worked for you
